version: "3.9"
services:
  asterisk:
    image: asterisk-test:latest
    build:
      context: .
    volumes:
      - type: bind
        source: /etc/recorded
        target: /etc/recorded
      - type: bind
        source: /var/log/asterisk
        target: /var/log/asterisk
    restart: always
    network_mode: "host"
    container_name: asterisk
  nginx:
    image: nginx:1.25.3-alpine
    network_mode: "host"
    container_name: nginx
    volumes:
      - ${PWD}/etc/nginx/default:/etc/nginx/conf.d/default.conf
      - type: bind
        source: /etc/recorded
        target: /etc/recorded
    command: 'nginx -g "daemon off;"'
    restart: on-failure
    environment:
      ENTRYPOINT_QUIET_LOGS: 1
