version: "3.9"
services:
  asterisk:
    image: asterisk-test:latest
    build:
      context: .
    volumes:
      - type: bind
        source: /etc/recorded
        target: /etc/recorded
      - type: bind
        source: /var/log/asterisk
        target: /var/log/asterisk
    restart: always
    network_mode: "host"
