version: "3.9"
services:
  asterisk:
    image: asterisk-test:latest
    volumes:
      - musiconhold-data:/etc/moh
      - recorded-data:/etc/recorded
      - type: bind
        source: /var/log/asterisk
        target: /var/log/asterisk
    restart: always
    network_mode: "host"
    depends_on:
      mysql:
        condition: service_healthy
